artifacts_root: artifacts

# root directory for data ingestion artifacts 
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/farshidhesami/Branching-tutorial/raw/master/winequality-red.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

# root directory for data validation artifacts 
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  

# root directory for data transformation artifacts 
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv


# root directory for model_trainer artifacts
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib